env: prod
http:
  host: 0.0.0.0
  #  host: 127.0.0.1
  port: 8000
security:
  api_sign:
    app_key: my_app_key
    app_security: my_app_security
  jwt:
    key: my_jwt_key
data:
  db:
#    user:
#      driver: sqlite
#      dsn: storage/nunu-test.db?_busy_timeout=5000
    user:
      driver: my_db_driver
      dsn: my_db_dsn
  #    user:
  #      driver: postgres
  #      dsn: host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai
#  redis:
#    addr: 127.0.0.1:6350
#    password: ""
#    db: 0
#    read_timeout: 0.2s
#    write_timeout: 0.2s

log:
  log_level: info
  encoding: json           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true