// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"web-tool-go/internal/handler"
	"web-tool-go/internal/repository"
	"web-tool-go/internal/server"
	"web-tool-go/internal/service"
	"web-tool-go/pkg/app"
	"web-tool-go/pkg/jwt"
	"web-tool-go/pkg/log"
	"web-tool-go/pkg/server/http"
	"web-tool-go/pkg/sid"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	weiboMsgRepository := repository.NewWeiboMsgRepository(repositoryRepository)
	weiboMsgService := service.NewWeiboMsgService(serviceService, weiboMsgRepository)
	weiboMsgHandler := handler.NewWeiboMsgHandler(handlerHandler, weiboMsgService)
	weiboAccountRepository := repository.NewWeiboAccountRepository(repositoryRepository)
	weiboAccountService := service.NewWeiboAccountService(serviceService, weiboAccountRepository)
	weiboAccountHandler := handler.NewWeiboAccountHandler(handlerHandler, weiboAccountService)
	weiboStatisticsRepository := repository.NewWeiboStatisticsRepository(repositoryRepository)
	weiboStatisticsService := service.NewWeiboStatisticsService(serviceService, weiboStatisticsRepository)
	weiboStatisticsHandler := handler.NewWeiboStatisticsHandler(handlerHandler, weiboStatisticsService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, userHandler, weiboMsgHandler, weiboAccountHandler, weiboStatisticsHandler)
	job := server.NewJob(logger)
	appApp := newApp(httpServer, job)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewWeiboMsgRepository, repository.NewWeiboAccountRepository, repository.NewWeiboStatisticsRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewWeiboMsgService, service.NewWeiboAccountService, service.NewWeiboStatisticsService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewWeiboMsgHandler, handler.NewWeiboAccountHandler, handler.NewWeiboStatisticsHandler)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJob)

// build App
func newApp(
	httpServer *http.Server,
	job *server.Job,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, job), app.WithName("demo-server"))
}
